[2025-09-18T15:50:52.711+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:50:52.754+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:50:52.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:50:52.767+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:50:52.783+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:50:52.790+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp5ba1q2cb']
[2025-09-18T15:50:52.791+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13586) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:50:52.793+0000] {standard_task_runner.py:91} INFO - Job 243: Subtask wait_for_ready_flag
[2025-09-18T15:50:52.793+0000] {standard_task_runner.py:64} INFO - Started process 13587 to run task
[2025-09-18T15:50:52.870+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:50:53.005+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:50:53.007+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:50:53.021+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:50:53.022+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:50:53.022+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:50:53.062+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:50:53.091+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:50:53.120+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:50:53.122+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:03.907+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:03.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:03.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:03.961+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:03.979+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:03.986+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp4pkbdstc']
[2025-09-18T15:51:03.987+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13593) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:03.988+0000] {standard_task_runner.py:91} INFO - Job 244: Subtask wait_for_ready_flag
[2025-09-18T15:51:03.988+0000] {standard_task_runner.py:64} INFO - Started process 13594 to run task
[2025-09-18T15:51:04.071+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:04.184+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:04.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:04.200+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f6a0>
[2025-09-18T15:51:04.201+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:04.201+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:04.228+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:04.244+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:04.274+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:04.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:15.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:15.177+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:15.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:15.186+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:15.205+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:15.213+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13610) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:15.213+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpom4llo8s']
[2025-09-18T15:51:15.214+0000] {standard_task_runner.py:64} INFO - Started process 13611 to run task
[2025-09-18T15:51:15.215+0000] {standard_task_runner.py:91} INFO - Job 245: Subtask wait_for_ready_flag
[2025-09-18T15:51:15.302+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:15.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:15.411+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:15.423+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f6a0>
[2025-09-18T15:51:15.424+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:15.424+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:15.449+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:15.470+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:15.500+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:15.507+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:26.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:26.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:26.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:26.132+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:26.149+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:26.156+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13612) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:26.157+0000] {standard_task_runner.py:64} INFO - Started process 13613 to run task
[2025-09-18T15:51:26.156+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpaq37degz']
[2025-09-18T15:51:26.158+0000] {standard_task_runner.py:91} INFO - Job 246: Subtask wait_for_ready_flag
[2025-09-18T15:51:26.238+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:26.342+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:26.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:26.355+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:51:26.356+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:26.357+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:26.381+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:26.412+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:26.443+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:26.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:37.114+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:37.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:37.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:37.164+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:37.185+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:37.194+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13619) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:37.193+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpj7vp5wtg']
[2025-09-18T15:51:37.196+0000] {standard_task_runner.py:64} INFO - Started process 13620 to run task
[2025-09-18T15:51:37.196+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask wait_for_ready_flag
[2025-09-18T15:51:37.282+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:37.387+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:37.390+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:37.401+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:51:37.402+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:37.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:37.427+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:37.451+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:37.483+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:37.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:48.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:48.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:48.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:48.304+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:48.323+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:48.333+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13636) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:48.331+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpd1vfxehk']
[2025-09-18T15:51:48.334+0000] {standard_task_runner.py:64} INFO - Started process 13637 to run task
[2025-09-18T15:51:48.334+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask wait_for_ready_flag
[2025-09-18T15:51:48.420+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:48.514+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:48.516+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:48.527+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:51:48.529+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:48.529+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:48.555+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:48.589+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:48.627+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:48.634+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:51:59.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:51:59.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:59.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:51:59.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:51:59.450+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:51:59.458+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13638) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:51:59.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpa22ovpql']
[2025-09-18T15:51:59.461+0000] {standard_task_runner.py:64} INFO - Started process 13639 to run task
[2025-09-18T15:51:59.461+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask wait_for_ready_flag
[2025-09-18T15:51:59.567+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:51:59.687+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:51:59.688+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:51:59.702+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:51:59.703+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:51:59.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:51:59.729+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:51:59.758+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:51:59.788+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:51:59.795+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:52:10.480+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:52:10.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:10.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:10.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:52:10.545+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:52:10.553+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13645) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:52:10.552+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpvauwul48']
[2025-09-18T15:52:10.555+0000] {standard_task_runner.py:64} INFO - Started process 13646 to run task
[2025-09-18T15:52:10.555+0000] {standard_task_runner.py:91} INFO - Job 250: Subtask wait_for_ready_flag
[2025-09-18T15:52:10.636+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:52:10.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:52:10.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:52:10.758+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:52:10.758+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:52:10.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:52:10.783+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:52:10.810+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:52:10.842+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:52:10.849+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:52:21.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:52:22.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:22.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:22.032+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:52:22.050+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:52:22.059+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13662) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:52:22.058+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpwcz8hze3']
[2025-09-18T15:52:22.061+0000] {standard_task_runner.py:64} INFO - Started process 13663 to run task
[2025-09-18T15:52:22.061+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask wait_for_ready_flag
[2025-09-18T15:52:22.146+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:52:22.246+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:52:22.247+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:52:22.258+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:52:22.259+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:52:22.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:52:22.282+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:52:22.317+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:52:22.374+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:52:22.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:52:33.274+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:52:33.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:33.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:33.339+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:52:33.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:52:33.370+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13669) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:52:33.372+0000] {standard_task_runner.py:64} INFO - Started process 13670 to run task
[2025-09-18T15:52:33.370+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpl4ket05c']
[2025-09-18T15:52:33.373+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask wait_for_ready_flag
[2025-09-18T15:52:33.474+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:52:33.594+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:52:33.596+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:52:33.608+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:52:33.608+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:52:33.609+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:52:33.633+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:52:33.668+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:52:33.704+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:52:33.711+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:52:44.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:52:44.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:44.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:44.532+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:52:44.548+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:52:44.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpq5poc4t3']
[2025-09-18T15:52:44.557+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13676) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:52:44.558+0000] {standard_task_runner.py:91} INFO - Job 253: Subtask wait_for_ready_flag
[2025-09-18T15:52:44.559+0000] {standard_task_runner.py:64} INFO - Started process 13677 to run task
[2025-09-18T15:52:44.648+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:52:44.753+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:52:44.754+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:52:44.765+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:52:44.766+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:52:44.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:52:44.790+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:52:44.814+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:52:44.846+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:52:44.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:52:55.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:52:55.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:55.763+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:52:55.764+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:52:55.781+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:52:55.790+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13688) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:52:55.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpzmn1paib']
[2025-09-18T15:52:55.791+0000] {standard_task_runner.py:64} INFO - Started process 13689 to run task
[2025-09-18T15:52:55.792+0000] {standard_task_runner.py:91} INFO - Job 254: Subtask wait_for_ready_flag
[2025-09-18T15:52:55.880+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:52:55.993+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:52:55.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:52:56.007+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:52:56.008+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:52:56.008+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:52:56.034+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:52:56.046+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:52:56.079+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:52:56.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:53:07.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:53:07.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:07.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:07.242+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:53:07.260+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:53:07.269+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13695) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:53:07.270+0000] {standard_task_runner.py:64} INFO - Started process 13696 to run task
[2025-09-18T15:53:07.268+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpd7907bgo']
[2025-09-18T15:53:07.271+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask wait_for_ready_flag
[2025-09-18T15:53:07.362+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:53:07.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:53:07.480+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:53:07.495+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:53:07.495+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:53:07.496+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:53:07.532+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:53:07.566+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:53:07.604+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:53:07.616+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:53:17.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:53:17.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:17.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:17.929+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:53:17.950+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:53:17.957+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13712) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:53:17.958+0000] {standard_task_runner.py:64} INFO - Started process 13713 to run task
[2025-09-18T15:53:17.957+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpvo6ayn5i']
[2025-09-18T15:53:17.959+0000] {standard_task_runner.py:91} INFO - Job 256: Subtask wait_for_ready_flag
[2025-09-18T15:53:18.030+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:53:18.135+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:53:18.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:53:18.150+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:53:18.151+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:53:18.151+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:53:18.178+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:53:18.213+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:53:18.263+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:53:18.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:53:29.168+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:53:29.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:29.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:29.218+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:53:29.237+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:53:29.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13714) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:53:29.248+0000] {standard_task_runner.py:64} INFO - Started process 13715 to run task
[2025-09-18T15:53:29.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpv54djx9g']
[2025-09-18T15:53:29.249+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask wait_for_ready_flag
[2025-09-18T15:53:29.331+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:53:29.445+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:53:29.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:53:29.459+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:53:29.461+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:53:29.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:53:29.488+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:53:29.504+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:53:29.538+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:53:29.545+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:53:40.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:53:40.463+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:40.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:40.471+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:53:40.488+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:53:40.495+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13721) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:53:40.495+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpc8jey1ai']
[2025-09-18T15:53:40.497+0000] {standard_task_runner.py:64} INFO - Started process 13722 to run task
[2025-09-18T15:53:40.497+0000] {standard_task_runner.py:91} INFO - Job 258: Subtask wait_for_ready_flag
[2025-09-18T15:53:40.572+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:53:40.677+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:53:40.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:53:40.693+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:53:40.695+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:53:40.695+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:53:40.722+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:53:40.751+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:53:40.792+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:53:40.799+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:53:51.310+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:53:51.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:51.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:53:51.358+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:53:51.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:53:51.381+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13738) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:53:51.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp47o10mep']
[2025-09-18T15:53:51.382+0000] {standard_task_runner.py:64} INFO - Started process 13739 to run task
[2025-09-18T15:53:51.382+0000] {standard_task_runner.py:91} INFO - Job 259: Subtask wait_for_ready_flag
[2025-09-18T15:53:51.463+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:53:51.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:53:51.569+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:53:51.583+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:53:51.583+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:53:51.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:53:51.609+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:53:51.638+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:53:51.671+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:53:51.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:54:01.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:54:01.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:01.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:01.884+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:54:01.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:54:01.908+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13740) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:54:01.909+0000] {standard_task_runner.py:64} INFO - Started process 13741 to run task
[2025-09-18T15:54:01.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpdy3dmp43']
[2025-09-18T15:54:01.910+0000] {standard_task_runner.py:91} INFO - Job 260: Subtask wait_for_ready_flag
[2025-09-18T15:54:01.987+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:54:02.087+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:54:02.090+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:54:02.101+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:54:02.103+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:54:02.103+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:54:02.127+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:54:02.164+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:54:02.196+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:54:02.203+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:54:13.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:54:13.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:13.166+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:13.167+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:54:13.184+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:54:13.193+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13747) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:54:13.192+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpjlfv4kda']
[2025-09-18T15:54:13.195+0000] {standard_task_runner.py:64} INFO - Started process 13748 to run task
[2025-09-18T15:54:13.195+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask wait_for_ready_flag
[2025-09-18T15:54:13.285+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:54:13.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:54:13.402+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:54:13.416+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:54:13.417+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:54:13.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:54:13.449+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:54:13.490+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:54:13.528+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:54:13.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:54:24.035+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:54:24.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:24.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:54:24.087+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:54:24.106+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:54:24.115+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=13764) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:54:24.113+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpzidkjwot']
[2025-09-18T15:54:24.116+0000] {standard_task_runner.py:64} INFO - Started process 13765 to run task
[2025-09-18T15:54:24.117+0000] {standard_task_runner.py:91} INFO - Job 262: Subtask wait_for_ready_flag
[2025-09-18T15:54:24.197+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 0d34ce0f8ee7
[2025-09-18T15:54:24.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:54:24.307+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:54:24.319+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7a0ba795f740>
[2025-09-18T15:54:24.320+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:54:24.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:54:24.345+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:54:24.372+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:54:24.406+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:54:24.412+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:57:54.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:57:54.958+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:57:54.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:57:54.972+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:57:54.995+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:57:55.004+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpmf3y9wtl']
[2025-09-18T15:57:55.009+0000] {standard_task_runner.py:91} INFO - Job 264: Subtask wait_for_ready_flag
[2025-09-18T15:57:55.013+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:57:55.014+0000] {standard_task_runner.py:64} INFO - Started process 171 to run task
[2025-09-18T15:57:55.138+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:57:55.282+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:57:55.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:57:55.298+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a373ec00>
[2025-09-18T15:57:55.299+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:57:55.300+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:57:55.332+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:57:55.350+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:57:55.389+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:57:55.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:58:05.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:58:05.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:05.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:05.853+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:58:05.867+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:58:05.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpldxaegtu']
[2025-09-18T15:58:05.877+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask wait_for_ready_flag
[2025-09-18T15:58:05.881+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:58:05.883+0000] {standard_task_runner.py:64} INFO - Started process 187 to run task
[2025-09-18T15:58:05.966+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:58:06.074+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:58:06.075+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:58:06.087+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746a20>
[2025-09-18T15:58:06.088+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:58:06.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:58:06.116+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:58:06.137+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:58:06.178+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:58:06.183+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:58:16.996+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:58:17.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:17.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:17.065+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:58:17.082+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:58:17.093+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpjke8ozak']
[2025-09-18T15:58:17.098+0000] {standard_task_runner.py:91} INFO - Job 266: Subtask wait_for_ready_flag
[2025-09-18T15:58:17.103+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:58:17.105+0000] {standard_task_runner.py:64} INFO - Started process 189 to run task
[2025-09-18T15:58:17.217+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:58:17.359+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:58:17.361+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:58:17.376+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746a20>
[2025-09-18T15:58:17.379+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:58:17.379+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:58:17.409+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:58:17.441+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:58:17.479+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:58:17.483+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:58:28.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:58:28.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:28.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:28.283+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:58:28.348+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:58:28.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp96w52_wm']
[2025-09-18T15:58:28.362+0000] {standard_task_runner.py:91} INFO - Job 267: Subtask wait_for_ready_flag
[2025-09-18T15:58:28.367+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:58:28.368+0000] {standard_task_runner.py:64} INFO - Started process 211 to run task
[2025-09-18T15:58:28.459+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:58:28.743+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:58:28.745+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:58:28.757+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746a20>
[2025-09-18T15:58:28.757+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:58:28.758+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:58:28.795+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:58:28.824+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:58:28.858+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:58:28.866+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:58:39.570+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:58:39.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:39.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:39.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:58:39.637+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:58:39.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpfzz0cna3']
[2025-09-18T15:58:39.650+0000] {standard_task_runner.py:91} INFO - Job 268: Subtask wait_for_ready_flag
[2025-09-18T15:58:39.653+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:58:39.654+0000] {standard_task_runner.py:64} INFO - Started process 213 to run task
[2025-09-18T15:58:39.732+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:58:39.837+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:58:39.838+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:58:39.852+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746a20>
[2025-09-18T15:58:39.853+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:58:39.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:58:39.875+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:58:39.909+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:58:39.943+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:58:39.948+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:58:50.608+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:58:50.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:50.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:58:50.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:58:50.673+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:58:50.679+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp3pd0g657']
[2025-09-18T15:58:50.683+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask wait_for_ready_flag
[2025-09-18T15:58:50.688+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:58:50.689+0000] {standard_task_runner.py:64} INFO - Started process 215 to run task
[2025-09-18T15:58:50.764+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:58:50.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:58:50.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:58:50.881+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746a20>
[2025-09-18T15:58:50.882+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:58:50.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:58:50.905+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:58:50.944+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:58:50.976+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:58:50.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:01.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:01.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:01.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:01.893+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:01.910+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:01.917+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpwhfe_3c8']
[2025-09-18T15:59:01.920+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask wait_for_ready_flag
[2025-09-18T15:59:01.925+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:01.926+0000] {standard_task_runner.py:64} INFO - Started process 237 to run task
[2025-09-18T15:59:02.011+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:02.122+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:02.124+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:02.136+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ac0>
[2025-09-18T15:59:02.137+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:02.138+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:02.163+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:02.181+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:02.211+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:02.219+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:13.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:13.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:13.171+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:13.172+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:13.190+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:13.198+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpn_9r4_8k']
[2025-09-18T15:59:13.201+0000] {standard_task_runner.py:91} INFO - Job 271: Subtask wait_for_ready_flag
[2025-09-18T15:59:13.205+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:13.206+0000] {standard_task_runner.py:64} INFO - Started process 239 to run task
[2025-09-18T15:59:13.293+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:13.402+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:13.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:13.415+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746b60>
[2025-09-18T15:59:13.415+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:13.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:13.440+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:13.461+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:13.493+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:13.500+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:24.388+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:24.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:24.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:24.433+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:24.449+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:24.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpot1t4du2']
[2025-09-18T15:59:24.460+0000] {standard_task_runner.py:91} INFO - Job 272: Subtask wait_for_ready_flag
[2025-09-18T15:59:24.464+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:24.465+0000] {standard_task_runner.py:64} INFO - Started process 241 to run task
[2025-09-18T15:59:24.545+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:24.646+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:24.649+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:24.660+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746b60>
[2025-09-18T15:59:24.661+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:24.661+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:24.684+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:24.719+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:24.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:24.772+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:35.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:35.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:35.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:35.638+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:35.657+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:35.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpoaiylxkx']
[2025-09-18T15:59:35.669+0000] {standard_task_runner.py:91} INFO - Job 273: Subtask wait_for_ready_flag
[2025-09-18T15:59:35.672+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:35.673+0000] {standard_task_runner.py:64} INFO - Started process 263 to run task
[2025-09-18T15:59:35.749+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:35.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:35.859+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:35.871+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746b60>
[2025-09-18T15:59:35.872+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:35.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:35.901+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:35.928+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:35.960+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:35.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:46.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:46.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:46.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:46.625+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:46.644+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:46.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp0gjykwi9']
[2025-09-18T15:59:46.657+0000] {standard_task_runner.py:91} INFO - Job 274: Subtask wait_for_ready_flag
[2025-09-18T15:59:46.660+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:46.661+0000] {standard_task_runner.py:64} INFO - Started process 265 to run task
[2025-09-18T15:59:46.751+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:46.859+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:46.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:46.873+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746c00>
[2025-09-18T15:59:46.874+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:46.874+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:46.899+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:46.916+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:46.949+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:46.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T15:59:57.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T15:59:57.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:57.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T15:59:57.876+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T15:59:57.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T15:59:57.896+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpcpdw5jjx']
[2025-09-18T15:59:57.898+0000] {standard_task_runner.py:91} INFO - Job 275: Subtask wait_for_ready_flag
[2025-09-18T15:59:57.902+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T15:59:57.903+0000] {standard_task_runner.py:64} INFO - Started process 267 to run task
[2025-09-18T15:59:57.976+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T15:59:58.072+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T15:59:58.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T15:59:58.085+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T15:59:58.086+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T15:59:58.087+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T15:59:58.107+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T15:59:58.117+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T15:59:58.144+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T15:59:58.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:00:09.136+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:00:09.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:09.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:09.180+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:00:09.196+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:00:09.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpzc0zeyir']
[2025-09-18T16:00:09.206+0000] {standard_task_runner.py:91} INFO - Job 276: Subtask wait_for_ready_flag
[2025-09-18T16:00:09.210+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:00:09.211+0000] {standard_task_runner.py:64} INFO - Started process 289 to run task
[2025-09-18T16:00:09.298+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:00:09.418+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:00:09.420+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:00:09.434+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746c00>
[2025-09-18T16:00:09.435+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:00:09.436+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:00:09.462+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:00:09.506+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:00:09.546+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:00:09.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:00:20.284+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:00:20.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:20.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:20.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:00:20.353+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:00:20.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpwmkgy48h']
[2025-09-18T16:00:20.364+0000] {standard_task_runner.py:91} INFO - Job 277: Subtask wait_for_ready_flag
[2025-09-18T16:00:20.368+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:00:20.369+0000] {standard_task_runner.py:64} INFO - Started process 291 to run task
[2025-09-18T16:00:20.449+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:00:20.557+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:00:20.558+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:00:20.570+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746c00>
[2025-09-18T16:00:20.571+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:00:20.571+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:00:20.595+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:00:20.623+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:00:20.653+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:00:20.659+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:00:31.622+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:00:31.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:31.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:31.683+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:00:31.703+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:00:31.712+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpxig1nxo6']
[2025-09-18T16:00:31.716+0000] {standard_task_runner.py:91} INFO - Job 278: Subtask wait_for_ready_flag
[2025-09-18T16:00:31.720+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:00:31.721+0000] {standard_task_runner.py:64} INFO - Started process 313 to run task
[2025-09-18T16:00:31.814+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:00:31.942+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:00:31.943+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:00:31.958+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:00:31.959+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:00:31.959+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:00:31.986+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:00:32.017+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:00:32.056+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:00:32.064+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:00:42.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:00:42.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:42.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:42.576+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:00:42.592+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:00:42.600+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp2hjpfp71']
[2025-09-18T16:00:42.603+0000] {standard_task_runner.py:91} INFO - Job 279: Subtask wait_for_ready_flag
[2025-09-18T16:00:42.606+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=314) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:00:42.608+0000] {standard_task_runner.py:64} INFO - Started process 315 to run task
[2025-09-18T16:00:42.690+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:00:42.798+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:00:42.800+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:00:42.813+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:00:42.814+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:00:42.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:00:42.840+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:00:42.862+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:00:42.895+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:00:42.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:00:53.783+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:00:53.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:53.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:00:53.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:00:53.855+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:00:53.864+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp80nthd7l']
[2025-09-18T16:00:53.868+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask wait_for_ready_flag
[2025-09-18T16:00:53.871+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:00:53.872+0000] {standard_task_runner.py:64} INFO - Started process 317 to run task
[2025-09-18T16:00:53.953+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:00:54.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:00:54.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:00:54.081+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:00:54.082+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:00:54.083+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:00:54.110+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:00:54.128+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:00:54.162+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:00:54.169+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:01:04.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:01:05.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:05.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:05.041+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:01:05.057+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:01:05.064+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmparso09fg']
[2025-09-18T16:01:05.068+0000] {standard_task_runner.py:91} INFO - Job 281: Subtask wait_for_ready_flag
[2025-09-18T16:01:05.073+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=338) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:01:05.074+0000] {standard_task_runner.py:64} INFO - Started process 339 to run task
[2025-09-18T16:01:05.146+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:01:05.245+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:01:05.246+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:01:05.258+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:01:05.259+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:01:05.260+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:01:05.282+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:01:05.329+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:01:05.367+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:01:05.371+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:01:16.220+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:01:16.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:16.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:16.270+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:01:16.288+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:01:16.295+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpcdnsprts']
[2025-09-18T16:01:16.299+0000] {standard_task_runner.py:91} INFO - Job 282: Subtask wait_for_ready_flag
[2025-09-18T16:01:16.302+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:01:16.303+0000] {standard_task_runner.py:64} INFO - Started process 341 to run task
[2025-09-18T16:01:16.377+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:01:16.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:01:16.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:01:16.520+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:01:16.520+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:01:16.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:01:16.548+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:01:16.564+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:01:16.592+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:01:16.599+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:01:27.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:01:27.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:27.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:27.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:01:27.608+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:01:27.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp7z7_3s3i']
[2025-09-18T16:01:27.619+0000] {standard_task_runner.py:91} INFO - Job 283: Subtask wait_for_ready_flag
[2025-09-18T16:01:27.622+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=342) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:01:27.623+0000] {standard_task_runner.py:64} INFO - Started process 343 to run task
[2025-09-18T16:01:27.700+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:01:27.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:01:27.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:01:27.814+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:01:27.815+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:01:27.816+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:01:27.838+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:01:27.878+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:01:27.927+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:01:27.933+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:01:38.323+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:01:38.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:38.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:38.373+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:01:38.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:01:38.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpaf3w6bey']
[2025-09-18T16:01:38.402+0000] {standard_task_runner.py:91} INFO - Job 284: Subtask wait_for_ready_flag
[2025-09-18T16:01:38.407+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=364) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:01:38.408+0000] {standard_task_runner.py:64} INFO - Started process 365 to run task
[2025-09-18T16:01:38.481+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:01:38.586+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:01:38.587+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:01:38.598+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:01:38.599+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:01:38.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:01:38.623+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:01:38.663+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:01:38.706+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:01:38.713+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:01:49.517+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:01:49.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:49.566+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:01:49.567+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:01:49.586+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:01:49.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmptad7tzes']
[2025-09-18T16:01:49.601+0000] {standard_task_runner.py:91} INFO - Job 285: Subtask wait_for_ready_flag
[2025-09-18T16:01:49.604+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=366) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:01:49.604+0000] {standard_task_runner.py:64} INFO - Started process 367 to run task
[2025-09-18T16:01:49.686+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:01:49.790+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:01:49.791+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:01:49.804+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:01:49.805+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:01:49.806+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:01:49.833+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:01:49.859+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:01:49.893+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:01:49.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:00.738+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:00.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:00.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:00.791+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:00.816+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:00.824+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp_1i4ityy']
[2025-09-18T16:02:00.828+0000] {standard_task_runner.py:91} INFO - Job 286: Subtask wait_for_ready_flag
[2025-09-18T16:02:00.834+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=368) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:00.835+0000] {standard_task_runner.py:64} INFO - Started process 369 to run task
[2025-09-18T16:02:00.935+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:01.070+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:01.071+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:01.086+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:01.087+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:01.087+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:01.117+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:01.131+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:01.169+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:01.173+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:11.892+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:11.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:11.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:11.940+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:11.958+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:11.966+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpd78ornmp']
[2025-09-18T16:02:11.970+0000] {standard_task_runner.py:91} INFO - Job 287: Subtask wait_for_ready_flag
[2025-09-18T16:02:11.974+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:11.975+0000] {standard_task_runner.py:64} INFO - Started process 391 to run task
[2025-09-18T16:02:12.053+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:12.147+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:12.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:12.160+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:12.161+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:12.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:12.185+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:12.229+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:12.262+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:12.268+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:23.240+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:23.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:23.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:23.289+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:23.306+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:23.313+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmplgpt26e9']
[2025-09-18T16:02:23.316+0000] {standard_task_runner.py:91} INFO - Job 288: Subtask wait_for_ready_flag
[2025-09-18T16:02:23.320+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:23.321+0000] {standard_task_runner.py:64} INFO - Started process 393 to run task
[2025-09-18T16:02:23.404+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:23.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:23.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:23.517+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:23.517+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:23.518+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:23.543+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:23.576+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:23.610+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:23.616+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:34.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:34.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:34.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:34.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:34.296+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:34.304+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpa90ad_tc']
[2025-09-18T16:02:34.307+0000] {standard_task_runner.py:91} INFO - Job 289: Subtask wait_for_ready_flag
[2025-09-18T16:02:34.310+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:34.311+0000] {standard_task_runner.py:64} INFO - Started process 415 to run task
[2025-09-18T16:02:34.389+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:34.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:34.504+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:34.518+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:34.519+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:34.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:34.545+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:34.565+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:34.596+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:34.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:45.498+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:45.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:45.544+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:45.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:45.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:45.567+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpyjborsj2']
[2025-09-18T16:02:45.570+0000] {standard_task_runner.py:91} INFO - Job 290: Subtask wait_for_ready_flag
[2025-09-18T16:02:45.572+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=416) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:45.573+0000] {standard_task_runner.py:64} INFO - Started process 417 to run task
[2025-09-18T16:02:45.641+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:45.753+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:45.754+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:45.766+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:45.767+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:45.768+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:45.797+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:45.827+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:45.866+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:45.871+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:02:56.011+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:02:56.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:56.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:02:56.064+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:02:56.087+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:02:56.095+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpqdi6syc_']
[2025-09-18T16:02:56.098+0000] {standard_task_runner.py:91} INFO - Job 291: Subtask wait_for_ready_flag
[2025-09-18T16:02:56.102+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=418) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:02:56.103+0000] {standard_task_runner.py:64} INFO - Started process 419 to run task
[2025-09-18T16:02:56.424+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:02:56.527+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:02:56.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:02:56.543+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:02:56.544+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:02:56.545+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:02:56.566+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:02:56.600+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:02:56.633+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:02:56.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:03:07.011+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:03:07.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:07.062+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:07.063+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:03:07.078+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:03:07.085+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp5c_9s6le']
[2025-09-18T16:03:07.088+0000] {standard_task_runner.py:91} INFO - Job 292: Subtask wait_for_ready_flag
[2025-09-18T16:03:07.091+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=440) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:03:07.092+0000] {standard_task_runner.py:64} INFO - Started process 441 to run task
[2025-09-18T16:03:07.174+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:03:07.280+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:03:07.281+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:03:07.293+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:03:07.293+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:03:07.294+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:03:07.315+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:03:07.347+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:03:07.380+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:03:07.383+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:03:18.277+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:03:18.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:18.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:18.325+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:03:18.344+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:03:18.352+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpax4pkxzc']
[2025-09-18T16:03:18.355+0000] {standard_task_runner.py:91} INFO - Job 293: Subtask wait_for_ready_flag
[2025-09-18T16:03:18.358+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:03:18.359+0000] {standard_task_runner.py:64} INFO - Started process 443 to run task
[2025-09-18T16:03:18.446+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:03:18.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:03:18.555+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:03:18.569+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:03:18.569+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:03:18.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:03:18.597+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:03:18.614+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:03:18.646+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:03:18.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:03:29.376+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:03:29.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:29.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:29.424+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:03:29.441+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:03:29.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpn8d3085_']
[2025-09-18T16:03:29.452+0000] {standard_task_runner.py:91} INFO - Job 294: Subtask wait_for_ready_flag
[2025-09-18T16:03:29.455+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=444) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:03:29.456+0000] {standard_task_runner.py:64} INFO - Started process 445 to run task
[2025-09-18T16:03:29.534+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:03:29.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:03:29.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:03:29.657+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:03:29.658+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:03:29.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:03:29.685+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:03:29.711+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:03:29.742+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:03:29.748+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:03:40.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:03:40.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:40.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:40.366+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:03:40.383+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:03:40.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp27s89q30']
[2025-09-18T16:03:40.394+0000] {standard_task_runner.py:91} INFO - Job 295: Subtask wait_for_ready_flag
[2025-09-18T16:03:40.397+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:03:40.398+0000] {standard_task_runner.py:64} INFO - Started process 474 to run task
[2025-09-18T16:03:40.476+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:03:40.581+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:03:40.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:03:40.594+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746ca0>
[2025-09-18T16:03:40.594+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:03:40.595+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:03:40.618+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:03:40.653+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:03:40.686+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:03:40.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:03:51.646+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:03:51.685+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:51.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:03:51.694+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:03:51.713+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:03:51.721+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:03:51.720+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmphafsc0i1']
[2025-09-18T16:03:51.723+0000] {standard_task_runner.py:64} INFO - Started process 480 to run task
[2025-09-18T16:03:51.723+0000] {standard_task_runner.py:91} INFO - Job 296: Subtask wait_for_ready_flag
[2025-09-18T16:03:51.806+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:03:51.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:03:51.907+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:03:51.918+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:03:51.919+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:03:51.919+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:03:51.942+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:03:51.978+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:03:52.035+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:03:52.041+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:02.871+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:02.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:02.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:02.926+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:02.945+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:02.954+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=481) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:02.953+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpveue276t']
[2025-09-18T16:04:02.955+0000] {standard_task_runner.py:64} INFO - Started process 482 to run task
[2025-09-18T16:04:02.955+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask wait_for_ready_flag
[2025-09-18T16:04:03.043+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:03.157+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:03.159+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:03.172+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:04:03.173+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:03.174+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:03.198+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:03.210+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:03.243+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:03.249+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:13.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:13.718+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:13.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:13.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:13.748+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:13.758+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:13.756+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp3__nkoo0']
[2025-09-18T16:04:13.759+0000] {standard_task_runner.py:64} INFO - Started process 504 to run task
[2025-09-18T16:04:13.760+0000] {standard_task_runner.py:91} INFO - Job 298: Subtask wait_for_ready_flag
[2025-09-18T16:04:13.847+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:13.944+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:13.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:13.957+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:04:13.958+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:13.959+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:13.983+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:14.014+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:14.052+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:14.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:24.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:24.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:24.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:24.263+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:24.280+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:24.289+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=505) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:24.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpidfvb7ru']
[2025-09-18T16:04:24.291+0000] {standard_task_runner.py:64} INFO - Started process 506 to run task
[2025-09-18T16:04:24.291+0000] {standard_task_runner.py:91} INFO - Job 299: Subtask wait_for_ready_flag
[2025-09-18T16:04:24.373+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:24.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:24.479+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:24.492+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:04:24.493+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:24.493+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:24.519+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:24.546+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:24.579+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:24.586+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:35.523+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:35.559+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:35.568+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:35.568+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:35.586+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:35.593+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=507) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:35.595+0000] {standard_task_runner.py:64} INFO - Started process 508 to run task
[2025-09-18T16:04:35.593+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp_a5qc0eb']
[2025-09-18T16:04:35.596+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask wait_for_ready_flag
[2025-09-18T16:04:35.674+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:35.776+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:35.777+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:35.789+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:04:35.790+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:35.790+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:35.813+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:35.849+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:35.876+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:35.883+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:46.394+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:46.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:46.440+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:46.440+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:46.456+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:46.463+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=529) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:46.464+0000] {standard_task_runner.py:64} INFO - Started process 530 to run task
[2025-09-18T16:04:46.463+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpq72tm01y']
[2025-09-18T16:04:46.464+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask wait_for_ready_flag
[2025-09-18T16:04:46.549+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:46.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:46.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:46.679+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746d40>
[2025-09-18T16:04:46.680+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:46.680+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:46.707+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:46.718+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:46.750+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:46.757+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:04:57.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:04:57.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:57.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:04:57.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:04:57.881+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:04:57.887+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=531) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:04:57.889+0000] {standard_task_runner.py:64} INFO - Started process 532 to run task
[2025-09-18T16:04:57.887+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpp_4imehp']
[2025-09-18T16:04:57.889+0000] {standard_task_runner.py:91} INFO - Job 302: Subtask wait_for_ready_flag
[2025-09-18T16:04:57.960+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:04:58.057+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:04:58.058+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:04:58.069+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746de0>
[2025-09-18T16:04:58.070+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:04:58.070+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:04:58.092+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:04:58.103+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:04:58.134+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:04:58.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:05:08.925+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:05:08.962+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:08.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:08.971+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:05:08.990+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:05:08.999+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:05:08.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpk_7ckoa3']
[2025-09-18T16:05:09.001+0000] {standard_task_runner.py:64} INFO - Started process 554 to run task
[2025-09-18T16:05:09.001+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask wait_for_ready_flag
[2025-09-18T16:05:09.085+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:05:09.188+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:05:09.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:05:09.201+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746e80>
[2025-09-18T16:05:09.202+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:05:09.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:05:09.231+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:05:09.256+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:05:09.290+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:05:09.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:05:20.059+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:05:20.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:20.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:20.108+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:05:20.127+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:05:20.136+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=555) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:05:20.135+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpav0saupn']
[2025-09-18T16:05:20.138+0000] {standard_task_runner.py:64} INFO - Started process 556 to run task
[2025-09-18T16:05:20.138+0000] {standard_task_runner.py:91} INFO - Job 304: Subtask wait_for_ready_flag
[2025-09-18T16:05:20.226+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:05:20.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:05:20.329+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:05:20.341+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746e80>
[2025-09-18T16:05:20.342+0000] {sensor_branch.py:18} INFO - [DIAG] exists=False  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:05:20.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:05:20.369+0000] {taskinstance.py:2865} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-09-18T16:05:20.393+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:05:20.431+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:05:20.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-18T16:05:31.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:05:31.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:31.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:31.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:05:31.314+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_ready_flag> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:05:31.323+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:05:31.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'wait_for_ready_flag', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmpiins05z6']
[2025-09-18T16:05:31.325+0000] {standard_task_runner.py:64} INFO - Started process 563 to run task
[2025-09-18T16:05:31.325+0000] {standard_task_runner.py:91} INFO - Job 305: Subtask wait_for_ready_flag
[2025-09-18T16:05:31.409+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.wait_for_ready_flag manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:05:31.539+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='wait_for_ready_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:05:31.541+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:05:31.556+0000] {python.py:75} INFO - Poking callable: <function diag_file_is_ready at 0x7ce5a3746e80>
[2025-09-18T16:05:31.558+0000] {sensor_branch.py:18} INFO - [DIAG] exists=True  whoami=50000  ls(/opt/input)=<ERR listdir: [Errno 2] No such file or directory: '/opt/input'>
[2025-09-18T16:05:31.559+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-09-18T16:05:31.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:05:31.577+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sensor_branch_demo, task_id=wait_for_ready_flag, run_id=manual__2025-09-18T15:50:51.823082+00:00, execution_date=20250918T155051, start_date=20250918T160531, end_date=20250918T160531
[2025-09-18T16:05:31.620+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:05:31.655+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:05:31.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
